package com.botofholding.bot.CommandSetup;

import com.botofholding.bot.Config.CommandConfig;
import discord4j.core.object.command.ApplicationCommandOption;
import discord4j.discordjson.json.ApplicationCommandOptionChoiceData;
import discord4j.discordjson.json.ApplicationCommandOptionData;
import discord4j.discordjson.json.ApplicationCommandRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class CommandFactory {

    private final CommandConfig config;

    @Autowired
    public CommandFactory(CommandConfig config) {
        this.config = config;
    }

    public List<ApplicationCommandRequest> buildAllCommands() {
        List<ApplicationCommandRequest> commands = new ArrayList<>();
        commands.add(buildUserCommand());
        commands.add(buildContainerCommand());
        commands.add(buildItemCommand());
        commands.add(buildInventoryCommand());
        return commands;
    }

    private ApplicationCommandRequest buildUserCommand() {
        return ApplicationCommandRequest.builder()
                .name(config.getCmdUser())
                .description(config.getCmdUserDescription())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdUserUpdate())
                        .description(config.getSubcmdUserUpdateDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdUserGet())
                        .description(config.getSubcmdUserGetDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdUserSettings())
                        .description(config.getSubcmdUserSettingsDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionUserSettingsHideContainer())
                                .description(config.getOptionUserSettingsHideContainerDescription())
                                .type(ApplicationCommandOption.Type.BOOLEAN.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionUserSettingsHideUser())
                                .description(config.getOptionUserSettingsHideUserDescription())
                                .type(ApplicationCommandOption.Type.BOOLEAN.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionUserSettingsHideItem())
                                .description(config.getOptionUserSettingsHideItemDescription())
                                .type(ApplicationCommandOption.Type.BOOLEAN.getValue())
                                .build())
                        .build())
                .build();
    }

    private ApplicationCommandRequest buildItemCommand() {
        return ApplicationCommandRequest.builder()
                .name(config.getCmdItem())
                .description(config.getCmdItemDescription())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdItemFind())
                        .description(config.getSubcmdItemFindDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionName())
                                .description(config.getOptionItemFindNameDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .autocomplete(true)
                                .build())
                        .build())
                .build();
    }

    private ApplicationCommandRequest buildInventoryCommand() {
        return ApplicationCommandRequest.builder()
                .name(config.getCmdInventory())
                .description(config.getCmdInventoryDescription())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdInventoryAdd())
                        .description(config.getSubcmdInventoryAddDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionItem())
                                .description(config.getOptionInventoryAddItemDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .required(true)
                                .autocomplete(true)
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionQuantity())
                                .description(config.getOptionInventoryAddQuantityDescription())
                                .type(ApplicationCommandOption.Type.INTEGER.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionNote())
                                .description(config.getOptionInventoryAddNoteDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionInventoryAddParent())
                                .description(config.getOptionInventoryAddParentDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .autocomplete(true)
                                .build())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdInventoryDrop())
                        .description(config.getSubcmdInventoryDropDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionItem())
                                .description(config.getOptionInventoryDropItemDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .required(true)
                                .autocomplete(true)
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionQuantity())
                                .description(config.getOptionInventoryDropQuantityDescription())
                                .type(ApplicationCommandOption.Type.INTEGER.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionInventoryDropDropChildren())
                                .description(config.getOptionInventoryDropDropChildrenDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .choices(List.of(ApplicationCommandOptionChoiceData.builder().name("true").value("true").build()))
                                .build())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdInventoryModify())
                        .description(config.getSubcmdInventoryModifyDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionItem())
                                .description(config.getOptionInventoryModifyItemDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .required(true)
                                .autocomplete(true)
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionNote())
                                .description(config.getOptionInventoryModifyNoteDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionInventoryModifyMoveToRoot())
                                .description(config.getOptionInventoryModifyMoveToRootDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .choices(List.of(ApplicationCommandOptionChoiceData.builder().name("true").value("true").build()))
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionInventoryModifyMoveInside())
                                .description(config.getOptionInventoryModifyMoveInsideDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .autocomplete(true)
                                .build())
                        .build())
                .build();
    }

    private ApplicationCommandRequest buildContainerCommand() {
        return ApplicationCommandRequest.builder()
                .name(config.getCmdContainer())
                .description(config.getCmdContainerDescription())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdContainerAdd())
                        .description(config.getSubcmdContainerAddDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionName())
                                .description(config.getOptionContainerAddNameDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .required(true)
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionDescription())
                                .description(config.getOptionContainerAddDescriptionDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionType())
                                .description(config.getOptionContainerAddTypeDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionServerOwned())
                                .description(config.getOptionContainerAddServerOwnedDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .choices(List.of(ApplicationCommandOptionChoiceData.builder().name("true").value("true").build()))
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionContainerAddSetAsActive())
                                .description(config.getOptionContainerAddSetAsActiveDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .choices(List.of(ApplicationCommandOptionChoiceData.builder().name("true").value("true").build()))
                                .build())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdContainerFind())
                        .description(config.getSubcmdContainerFindDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionName())
                                .description(config.getOptionContainerFindNameDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .autocomplete(true)
                                .build())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdContainerFindActive())
                        .description(config.getSubcmdContainerFindActiveDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdContainerActivate())
                        .description(config.getSubcmdContainerActivateDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionName())
                                .description(config.getOptionContainerActivateNameDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .required(true)
                                .autocomplete(true)
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionPrioritize())
                                .description(config.getOptionContainerActivatePrioritizeDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .choices(List.of(
                                        ApplicationCommandOptionChoiceData.builder().name("Server Owned").value("GUILD").build(),
                                        ApplicationCommandOptionChoiceData.builder().name("User Owned").value("USER").build()
                                ))
                                .build())
                        .build())
                .addOption(ApplicationCommandOptionData.builder()
                        .name(config.getSubcmdContainerDelete())
                        .description(config.getSubcmdContainerDeleteDescription())
                        .type(ApplicationCommandOption.Type.SUB_COMMAND.getValue())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionName())
                                .description(config.getOptionContainerDeleteNameDescription())
                                .type(ApplicationCommandOption.Type.STRING.getValue())
                                .required(true)
                                .build())
                        .addOption(ApplicationCommandOptionData.builder()
                                .name(config.getOptionId())
                                .description(config.getOptionContainerDeleteIdDescription())
                                .type(ApplicationCommandOption.Type.INTEGER.getValue())
                                .required(true)
                                .build())
                        .build())
                .build();
    }
}
