USE [Bot_Of_Holding_DEV]
GO

/****** Object:  Table [dbo].[CNTNR_ITEM]    Script Date: 6/13/2025 11:38:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CNTNR_ITEM](
	[CNTNR_ITEM_ID] [numeric](9, 0) NOT NULL,
	[CNTNR_ID] [numeric](9, 0) NOT NULL,
	[ITEM_ID] [numeric](9, 0) NOT NULL,
	[ITM_QTY] [bigint] NOT NULL,
	[CRE_ID] [numeric](9, 0) NOT NULL,
	[CRE_DTTM] [datetime] NOT NULL,
	[LST_MDFD_ID] [numeric](9, 0) NOT NULL,
	[LST_MDFD_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK_CNTNR_ITEM] PRIMARY KEY CLUSTERED 
(
	[CNTNR_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CNTNR_ITEM] ADD  CONSTRAINT [DF_CNTNR_ITEM_CRE_DTTM]  DEFAULT (getdate()) FOR [CRE_DTTM]
GO

ALTER TABLE [dbo].[CNTNR_ITEM] ADD  CONSTRAINT [DF_CNTNR_ITEM_LST_MDFD_DTTM]  DEFAULT (getdate()) FOR [LST_MDFD_DTTM]
GO

ALTER TABLE [dbo].[CNTNR_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CNTNR_ITEM_CNTNR] FOREIGN KEY([CNTNR_ID])
REFERENCES [dbo].[USER_CNTNR] ([CNTNR_ID])
GO

ALTER TABLE [dbo].[CNTNR_ITEM] CHECK CONSTRAINT [FK_CNTNR_ITEM_CNTNR]
GO

ALTER TABLE [dbo].[CNTNR_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CNTNR_ITEM_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([item_id])
GO

ALTER TABLE [dbo].[CNTNR_ITEM] CHECK CONSTRAINT [FK_CNTNR_ITEM_ITEM]
GO

ALTER TABLE [dbo].[CNTNR_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CNTNR_ITEM_USER_DATA_CRE] FOREIGN KEY([CRE_ID])
REFERENCES [dbo].[USER_DATA] ([USER_ID])
GO

ALTER TABLE [dbo].[CNTNR_ITEM] CHECK CONSTRAINT [FK_CNTNR_ITEM_USER_DATA_CRE]
GO

ALTER TABLE [dbo].[CNTNR_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_CNTNR_ITEM_USER_DATA_MDFD] FOREIGN KEY([LST_MDFD_ID])
REFERENCES [dbo].[USER_DATA] ([USER_ID])
GO

ALTER TABLE [dbo].[CNTNR_ITEM] CHECK CONSTRAINT [FK_CNTNR_ITEM_USER_DATA_MDFD]
GO


