USE [Bot_Of_Holding_DEV]
GO

/****** Object:  Table [dbo].[CNTNR]    Script Date: 6/15/2025 3:24:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CNTNR](
	[CNTNR_ID] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
	[CNTNR_NME] [nvarchar](75) NULL,
	[CNTNR_DESC] [nvarchar](250) NULL,
	[CNTNR_TYPE_ID] [numeric](9, 0) NULL,
	[CNTNR_TYPE_DESC] [varchar](50) NULL,
	[ACTV_INDC] [char](1) NOT NULL,
	[CRE_DTTM] [datetime] NOT NULL,
	[LST_ACTV_DTTM] [datetime] NOT NULL,
	[LST_MDFD_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK_USER_CNTNR] PRIMARY KEY CLUSTERED 
(
	[CNTNR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CNTNR] ADD  CONSTRAINT [DF_USER_CNTNR_ACTV_INDC]  DEFAULT ('Y') FOR [ACTV_INDC]
GO

ALTER TABLE [dbo].[CNTNR] ADD  CONSTRAINT [DF_USER_CNTNR_CRE_DTTM]  DEFAULT (getdate()) FOR [CRE_DTTM]
GO

ALTER TABLE [dbo].[CNTNR] ADD  CONSTRAINT [DF_USER_CNTNR_LST_ACTV_DTTM]  DEFAULT (getdate()) FOR [LST_ACTV_DTTM]
GO

ALTER TABLE [dbo].[CNTNR] ADD  CONSTRAINT [DF_USER_CNTNR_LST_MDFD_DTTM]  DEFAULT (getdate()) FOR [LST_MDFD_DTTM]
GO

ALTER TABLE [dbo].[CNTNR]  WITH CHECK ADD  CONSTRAINT [CK_USER_CNTNR_ACTV_INDC] CHECK  (([ACTV_INDC]='N' OR [ACTV_INDC]='Y'))
GO

ALTER TABLE [dbo].[CNTNR] CHECK CONSTRAINT [CK_USER_CNTNR_ACTV_INDC]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Maps ownership of containers or items to respective owner types' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CNTNR'
GO


