USE [Bot_Of_Holding_DEV]
GO

/****** Object:  Table [dbo].[CNTNR_TYPE]    Script Date: 6/13/2025 11:47:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CNTNR_TYPE](
	[CNTNR_TYPE_ID] [numeric](9, 0) NOT NULL,
	[CNTNR_TYPE_NME] [nvarchar](50) NOT NULL,
	[CNTNR_TYPE_DESC] [nvarchar](250) NULL,
	[CRE_ID] [numeric](9, 0) NOT NULL,
	[CRE_DTTM] [datetime] NOT NULL,
	[LST_MDFD_ID] [numeric](9, 0) NOT NULL,
	[LST_MDFD_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK_CNTNR_TYPE] PRIMARY KEY CLUSTERED 
(
	[CNTNR_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CNTNR_TYPE] ADD  CONSTRAINT [DF_CNTNR_TYPE_CRE_DTTM]  DEFAULT (getdate()) FOR [CRE_DTTM]
GO

ALTER TABLE [dbo].[CNTNR_TYPE] ADD  CONSTRAINT [DF_CNTNR_TYPE_LST_MDFD_DTTM]  DEFAULT (getdate()) FOR [LST_MDFD_DTTM]
GO

ALTER TABLE [dbo].[CNTNR_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_CNTNR_TYPE_USER_DATA_CRE] FOREIGN KEY([CRE_ID])
REFERENCES [dbo].[USER_DATA] ([USER_ID])
GO

ALTER TABLE [dbo].[CNTNR_TYPE] CHECK CONSTRAINT [FK_CNTNR_TYPE_USER_DATA_CRE]
GO

ALTER TABLE [dbo].[CNTNR_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_CNTNR_TYPE_USER_DATA_MDFD] FOREIGN KEY([LST_MDFD_ID])
REFERENCES [dbo].[USER_DATA] ([USER_ID])
GO

ALTER TABLE [dbo].[CNTNR_TYPE] CHECK CONSTRAINT [FK_CNTNR_TYPE_USER_DATA_MDFD]
GO


