USE [Bot_Of_Holding_DEV]
GO

/****** Object:  Table [dbo].[USER_CNTNR]    Script Date: 6/15/2025 3:23:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_CNTNR](
	[USER_ID] [numeric](9, 0) NOT NULL,
	[CNTNR_ID] [numeric](9, 0) NOT NULL,
 CONSTRAINT [PK_USER_CNTNR_1] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[CNTNR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER_CNTNR]  WITH CHECK ADD  CONSTRAINT [FK_USER_CNTNR_CNTNR] FOREIGN KEY([CNTNR_ID])
REFERENCES [dbo].[CNTNR] ([CNTNR_ID])
GO

ALTER TABLE [dbo].[USER_CNTNR] CHECK CONSTRAINT [FK_USER_CNTNR_CNTNR]
GO

ALTER TABLE [dbo].[USER_CNTNR]  WITH CHECK ADD  CONSTRAINT [FK_USER_CNTNR_USER_DATA] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER_DATA] ([USER_ID])
GO

ALTER TABLE [dbo].[USER_CNTNR] CHECK CONSTRAINT [FK_USER_CNTNR_USER_DATA]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Join table between USER_DATA and CNTNR' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'USER_CNTNR'
GO


