USE [Bot_Of_Holding_DEV]
GO

/****** Object:  Table [dbo].[USER_DATA]    Script Date: 6/13/2025 11:31:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_DATA](
	[USER_ID] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
	[USR_DSCD_ID] [numeric](18, 0) NOT NULL,
	[USR_NME] [varchar](50) NULL,
	[CRE_DTTM] [datetime] NOT NULL,
	[LST_ACTV_DTTM] [datetime] NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UNIQUE_DSCD_ID_CNSTR] UNIQUE NONCLUSTERED 
(
	[USR_DSCD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER_DATA] ADD  CONSTRAINT [DF_USER_USR_NME]  DEFAULT ('') FOR [USR_NME]
GO

ALTER TABLE [dbo].[USER_DATA] ADD  CONSTRAINT [DF_USER_DATA_CRE_DTTM]  DEFAULT (getdate()) FOR [CRE_DTTM]
GO


